export const IMAGES_REQUESTED = 'IMAGES_REQUESTED';
export const IMAGES_COMPLETED = 'IMAGES_COMPLETED';
export const IMAGES_FAILED = 'IMAGES_FAILED';

export const SELECTED_IMAGES_REQUESTED = 'SELECTED_IMAGES_REQUESTED';
export const SELECTED_IMAGES_COMPLETED = 'SELECTED_IMAGES_COMPLETED';
export const SELECTED_IMAGES_FAILED = 'SELECTED_IMAGES_FAILED';

export const IMAGE_SELECTED = 'IMAGE_SELECTED';
export const IMAGE_DESELECTED = 'IMAGE_DESELECTED';

export const SELECTION_SAVE_REQUESTED = 'SELECTION_SAVE_REQUESTED';
export const SELECTION_SAVE_COMPLETED = 'SELECTION_SAVE_COMPLETED';
export const SELECTION_SAVE_FAILED = 'SELECTION_SAVE_FAILED';
